name: Run tests daily

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run tests
        env:
          SANDBOX_REPO_GITHUB_TOKEN: ${{secrets.SANDBOX_REPO_GITHUB_TOKEN}}
        run: bun run test
